name: build
run-name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone UnkownShadow200/ClassiCube
        run: git clone https://github.com/UnknownShadow200/ClassiCube
      - name: Create a symbolic link to `src/`
        run: ln -s ClassiCube/src/
      - name: Complile for Linux 64-bit
        run: gcc -shared -fPIC -o ServyvalPlugin.so ServyvalPlugin.c
      - uses: ./ClassiCube/.github/actions/upload_build
        with:
          SOURCE_FILE: 'ServyvalPlugin.so'
          DEST_NAME: 'ServyvalPlugin-Linux64.so'
